server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  profiles:
      active: dev
  http:
      multipart:
        max-file-size: 30Mb
        max-request-size: 30Mb
  devtools:
      restart:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰转换
  mapper-locations: mybatis/*Mapper.xml
  typeAliasesPackage: cn.code.chameleon.pojo , cn.code.chameleon.monitor.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true #分页参数合理化，最小值不能小于0，最大值不能超过行数
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  offsetAsPageNum: true #pageNum=offset pageSize=limit