-- MySQL Script generated by MySQL Workbench
-- Fri May 11 19:46:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chameleon
-- -----------------------------------------------------
-- 可定制化爬虫

-- -----------------------------------------------------
-- Schema chameleon
--
-- 可定制化爬虫
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chameleon` DEFAULT CHARACTER SET utf8 ;
USE `chameleon` ;

-- -----------------------------------------------------
-- Table `chameleon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `email` VARCHAR(45) NOT NULL COMMENT '用户邮箱',
  `password` VARCHAR(45) NOT NULL COMMENT '用户密码',
  `name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `status` INT NOT NULL COMMENT '用户状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `chameleon`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色id',
  `name` VARCHAR(45) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(100) NULL COMMENT '角色描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `chameleon`.`user_relation_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`user_relation_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户角色关联id',
  `user_id` BIGINT NOT NULL COMMENT '用户id',
  `role_id` BIGINT NOT NULL COMMENT '角色id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT NOT NULL COMMENT '操作人',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`),
  INDEX `user_key_idx` (`user_id` ASC),
  INDEX `role_key_idx` (`role_id` ASC),
  CONSTRAINT `user_role_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `chameleon`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_user_key`
    FOREIGN KEY (`role_id`)
    REFERENCES `chameleon`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户角色关联表';


-- -----------------------------------------------------
-- Table `chameleon`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`function` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '功能id',
  `code` VARCHAR(45) NOT NULL COMMENT '功能码',
  `description` VARCHAR(100) NOT NULL COMMENT '功能描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `extend_field` VARCHAR(45) NULL COMMENT '扩展字段',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '功能表';


-- -----------------------------------------------------
-- Table `chameleon`.`role_relation_function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`role_relation_function` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色功能关联id',
  `role_id` BIGINT NOT NULL COMMENT '角色id',
  `function_id` BIGINT NOT NULL COMMENT '功能id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT NOT NULL COMMENT '操作人',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`),
  INDEX `role_key_idx` (`role_id` ASC),
  INDEX `function_key_idx` (`function_id` ASC),
  CONSTRAINT `role_function_key`
    FOREIGN KEY (`role_id`)
    REFERENCES `chameleon`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `function_role_key`
    FOREIGN KEY (`function_id`)
    REFERENCES `chameleon`.`function` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chameleon`.`chameleon_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`chameleon_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '模版id',
  `domain` VARCHAR(100) NULL COMMENT '域名',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `template_config` TEXT NOT NULL COMMENT '配置json',
  `operator_id` BIGINT NOT NULL COMMENT '操作人',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '爬虫模版表';


-- -----------------------------------------------------
-- Table `chameleon`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '组id',
  `name` VARCHAR(45) NOT NULL COMMENT '组名',
  `description` VARCHAR(100) NULL COMMENT '组描述',
  `operator_id` BIGINT NOT NULL COMMENT '操作人',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '爬虫组';


-- -----------------------------------------------------
-- Table `chameleon`.`chameleon_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`chameleon_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务id',
  `template_id` BIGINT NOT NULL COMMENT '模版id',
  `group_id` BIGINT NOT NULL COMMENT '爬虫组ID',
  `job_name` VARCHAR(45) NOT NULL COMMENT '工作名称',
  `job_group` VARCHAR(45) NOT NULL COMMENT '工作组',
  `job_class_name` VARCHAR(200) NULL COMMENT '任务执行类名称',
  `trigger_name` VARCHAR(45) NOT NULL COMMENT '触发器名称',
  `trigger_group` VARCHAR(45) NOT NULL COMMENT '触发器组名',
  `expression` VARCHAR(100) NULL COMMENT '表达式',
  `status` INT NOT NULL DEFAULT 0 COMMENT '任务状态',
  `need_sync` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否异步',
  `repeat_interval` BIGINT UNSIGNED NULL DEFAULT 0 COMMENT '重复间隔',
  `repeat_count` BIGINT UNSIGNED NULL DEFAULT 0 COMMENT '重复次数',
  `time_zone_id` VARCHAR(45) NULL COMMENT '时区id',
  `description` VARCHAR(100) NULL COMMENT '描述',
  `operator_id` BIGINT NOT NULL COMMENT '操作人',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`),
  INDEX `template_key_idx` (`template_id` ASC),
  INDEX `task_group_key_idx` (`group_id` ASC),
  CONSTRAINT `template_key`
    FOREIGN KEY (`template_id`)
    REFERENCES `chameleon`.`chameleon_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_group_key`
    FOREIGN KEY (`group_id`)
    REFERENCES `chameleon`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '爬虫任务表';


-- -----------------------------------------------------
-- Table `chameleon`.`chameleon_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`chameleon_statistics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务数据统计id',
  `task_id` BIGINT NOT NULL COMMENT '任务id',
  `crawl_count` BIGINT NOT NULL DEFAULT 0 COMMENT '爬取数量',
  `stop_count` INT NOT NULL DEFAULT 0 COMMENT '任务停止次数',
  `error_count` BIGINT NOT NULL DEFAULT 0 COMMENT '任务异常次数',
  `run_hours` BIGINT NOT NULL DEFAULT 0 COMMENT '运行时长',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`),
  INDEX `task_key_idx` (`task_id` ASC),
  CONSTRAINT `task_key`
    FOREIGN KEY (`task_id`)
    REFERENCES `chameleon`.`chameleon_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '任务数据统计表';


-- -----------------------------------------------------
-- Table `chameleon`.`service_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`service_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Service方法日志id',
  `class_name` VARCHAR(200) NOT NULL COMMENT '类名',
  `method_name` VARCHAR(200) NOT NULL COMMENT '方法名',
  `method_param` TEXT NULL COMMENT '方法参数',
  `return_value` TEXT NULL COMMENT '返回值',
  `time_cost` BIGINT NULL COMMENT '执行时间',
  `operator_id` BIGINT NOT NULL COMMENT '操作人id',
  `operator_name` VARCHAR(45) NOT NULL COMMENT '操作人姓名',
  `invoke_status` INT NOT NULL DEFAULT 0 COMMENT '执行状态',
  `error_message` TEXT NULL COMMENT '错误信息',
  `add_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `parent_id` BIGINT NOT NULL COMMENT '父方法id',
  PRIMARY KEY (`id`),
  INDEX `idx_add_time` (`add_time` ASC),
  INDEX `idx_parent_id` (`parent_id` ASC))
ENGINE = InnoDB
COMMENT = 'service日志';


-- -----------------------------------------------------
-- Table `chameleon`.`mapper_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chameleon`.`mapper_log` (
  `id` BIGINT NOT NULL COMMENT 'mapper日志id',
  `serivce_log_id` BIGINT NULL COMMENT 'service日志id',
  `method_name` TEXT NOT NULL COMMENT '方法名称',
  `method_param` TEXT NULL COMMENT '方法参数',
  `target_table_name` VARCHAR(100) NOT NULL COMMENT '目标表名',
  `operate_type` TINYINT(3) NOT NULL COMMENT '操作类型',
  `influence_row` INT NULL DEFAULT 0 COMMENT '影响行数',
  `sql_statement` TEXT NOT NULL COMMENT 'sql语句',
  `invoke_status` INT NOT NULL DEFAULT 0 COMMENT '执行状态',
  `error_message` TEXT NULL COMMENT '错误信息',
  `add_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `time_cost` BIGINT NOT NULL COMMENT '执行时间',
  PRIMARY KEY (`id`),
  INDEX `idx_add_time` (`add_time` ASC),
  INDEX `serivce_log_id` (`serivce_log_id` ASC))
ENGINE = InnoDB
COMMENT = 'mapper日志表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
